# Generated by Django 5.1.1 on 2024-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
